Project Structure
tdmnew/ReactJSGlobalMentoring-Client pull request #11
Opened 2021-01-20 18:04 UTC by tdmnew

Hi,

The amendments to the project structure have been created (This meant re-commiting changes to the components folder done in the React and Code Structure pull request).

- .gitignore has been amended to ignore coverage
- The 'Core' folder has been created (As done in the previous pull)
- The 'HOCs' folder has been created with Context and Layout added
- 'Search' and 'Header' have been merged with 'MovieDetails'
- 'MovieCard' has been merged with 'MovieList'
- '.test.js' was added by mistake in a previous commit - I will remove this as soon as the pull requests have been approved.

Unfortunately, I chose the approach of using redux-toolkit slices to deal with reducers and actions, which is handling action creators and types for non-asynchronous use. However, I have created an actionTypes.js file which handles all saga action types now. 

I can't seem to find a way online to separate slice action types and creators, but if you can think of an approach please let me know (Otherwise, I will revert to using separate actions and reducers if preferred).

Thanks

2021-01-24 18:13 UTC, tdmnew commented
Hi Dmitry, 

I've spent some time today reviewing the comments you've made to the previous pull requests and attempted to rebase the changes.

As you correctly pointed out when highlighting issues you had with the React and Code Structure PR, the issue appears to be that the work was behind previous commits. As you can likely tell by the commit history, I have caused enough damage (!!!) attempting to revert, fix and merge these changes. 

I have added another commit to this PR which includes the most up-to-date changes from that PR and previous ones up until now. This includes some additional things I had been working on while awaiting your PR review (i.e. a 'custom' dropdown and loading spinner for images). 

I will await your advice before proceeding further. Apologies for the issues this has caused - lessons certainly have been learned.

Thanks

2021-01-25 10:55 UTC, tdmnew commented
Okay, I've changed some of the files in React-Review to keep it up-to-date with the Webpack PR (And allow it to run). Unfortunately, there's now a number of merge conflicts due. Will resolve once you've checked over these PRs (Alternatively, I will revert this PR).

2021-01-25 12:08 UTC, Dmitry-White requested changes
Nice job!
That's a lot of work from you!
A general piece of advice regarding the whole code base: try keeping the imports grouped and organized with empty line between different groups. It's always a lot easier to keep track of changes and conflicts when imports follow a certain number of rules.

2021-01-25 12:08 UTC, Dmitry-White commented on src/Components/Image/Image.js
> +import { IMG_FALLBACK } from '../../Core/Constants';
Don't forget to separate different levels of imports

2021-01-25 12:08 UTC, Dmitry-White commented on src/Components/Modals/AddMovie/AddMovie.js
> +import Dropdown from '../Dropdown.js';
Same as above - this import should follow the I18N_KEYS import and be separated with an empty line.

2021-01-25 12:08 UTC, Dmitry-White commented on src/Components/Modals/AddMovie/AddMovie.js
>                              onClick={formik.handleReset}
There's this thing called "spaghetti code" - in React it's called "spaghetti JSX".
So to avoid creating endless JSX in a single render/return, it's a good practice to create function in the current component scope that hold different parts of JSX code.
E.g. this div with className="container buttons" and all its children could be a separate function "renderButtons" that you call within the JSXto include its code there.
Consider doing the same for button with className="container__close-btn" (name might be "renderCloseButton") and the form itself (name might be "renderForm"). Same could be done with the form itself ("renderRuntimeLabel", "renderOverviewLabel" etc)

This will greatly improve your component readability and in the larger project - even allow for reuse of different "render*" function as separate components for other forms in your app.

2021-01-25 12:08 UTC, Dmitry-White commented on src/Components/Modals/Dropdown.js
> +        <label className="dropdown option" key={nanoid()}>
Be aware that usage of and UUID generators as input values for "key" in a list could lead to performance issues in some cases.
https://stackoverflow.com/questions/52705335/will-using-uuid-to-as-list-keys-cause-unnecessary-re-renders-in-react

2021-01-25 12:08 UTC, Dmitry-White commented on src/Components/Modals/EditMovie/EditMovie.js
> -import React from "react";
Same as for AddMovie component.

2021-01-25 12:08 UTC, Dmitry-White commented on src/Components/Modals/RootModal.js
> +import DeleteMovie from './DeleteMovie/DeleteMovie.js';
Consider changing the order of imports so that a more closely related imports to the current file come later in the import section and are separated with an empty line.
This might seem as a minor change until you work on a project with lots of imports and with a much stricter ESLint configuration.

2021-01-25 12:08 UTC, Dmitry-White commented on src/Components/Modals/__tests__/RootModal.test.js
> +import store from '../../../Store/index.js';
When it comes to tests the order of imports might be a lot more "damage-causing" since often you need to mock some of the imported modules without other modules causing conflicts.
So following the above comment on the order of imports as a default implementation detail might save you some time.

2021-01-25 12:08 UTC, Dmitry-White commented on src/Components/MovieDetails/MovieDetails.js
> +                        <Loader height={190} width={80} color={'#f65261'} />
If you want to maintain a single theme across your app, it's a good practice to keep these css colours in a Core/constants folder.

2021-01-25 12:08 UTC, Dmitry-White commented on src/Components/MovieList/MovieCard/MovieCard.js
> +            modalProps: { type: 'Delete Movie', info: { id } },
Since there're a number of different files where you're using these string type props for your Modals, it's probably a good idea to store them in Core/constants.

2021-01-26 15:33 UTC, tdmnew commented
Apologies for the cluttered commit history - I had several issues with merging when I rebased. I think I've covered the import order issue in each file, unless there was a problem when manually editing when there were merge conflicts.

2021-02-24 13:32 UTC, Dmitry-White approved these changes

2021-02-24 13:36 UTC, merged